{{- if and (not .Values.existingSecret.name) .Values.apiToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "betterstack-monitor-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "betterstack-monitor-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.apiToken | quote }}
{{- end }}
